interface Article {
  createdDate: string // 創建日期
  title: string // 文章標題
  tags: string[] // 標籤
  redirectUrl: string // 文章網址
}

export const articles: Article[] = [
  {
    createdDate: '2022-10-18',
    title: '將日常風景揉進土裡－專訪「野火製陶」主理人 Jea，一窺陶土樸拙而多變的表情',
    tags: ['專訪', 'wonder'],
    redirectUrl: 'https://wonder.am/2022/10/18/interview-wildfire-studio/',
  },
  {
    createdDate: '2022-10-23',
    title: '高雄市區散散步！探索港都最接地氣的美味日常，就由火鍋、咖啡、日料餐廳來收藏城市的專屬風味',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2022/10/23/one-day-in-kaohsiung-trip/',
  },
  {
    createdDate: '2022-12-12',
    title: '專訪台灣新銳唱片設計師于薇：「我擅長的風格，可能是有點陰暗？」',
    tags: ['專訪', '生活圈'],
    redirectUrl: 'https://zh.soundoflife.com/blogs/design/grammy-awards-best-recording-package-taiwanese-album-cover-designer-yu-wei?_pos=3&_sid=8cb346ca7&_ss=r',
  },
  {
    createdDate: '2023-01-17',
    title: '專訪唱片設計師李政瀚：用日系美式風格混搭在地生活創意',
    tags: ['專訪', '生活圈'],
    redirectUrl: 'https://zh.soundoflife.com/blogs/design/grammy-awards-best-recording-package-taiwanese-album-cover-designer-li-jheng-han-interview?_pos=8&_sid=8cb346ca7&_ss=r',
  },
  {
    createdDate: '2022-10-23',
    title: '宛如置身在京都！走進新竹老宅咖啡館「Ça va小日和」，感受寧靜而美好的時刻',
    tags: ['外稿', 'readyGo'],
    redirectUrl: 'https://imreadygo.com/121913/',
  },
  {
    createdDate: '2022-12-31',
    title: '在仁武宮旁喝咖啡！嘉義「Supiidoスピード」，充滿日式風格的街邊小店',
    tags: ['外稿', 'readyGo'],
    redirectUrl: 'https://imreadygo.com/126273/',
  },
  {
    createdDate: '2023-01-02',
    title: '誰說台味就是俗？踏進嘉義復古質感餐廳「弄，來小餐桌」，品嘗平凡又深刻的滋味！',
    tags: ['外稿', 'readyGo'],
    redirectUrl: 'https://imreadygo.com/126271/',
  },
  {
    createdDate: '2022-11-28',
    title: '母愛滿出來！專訪主播媽咪戴心怡：「我的人生中不能夠沒有我的小孩。」',
    tags: ['專訪', '花嫁'],
    redirectUrl: 'https://www.luxewed.asia/People/%e3%80%90luxewed%e2%94%82%e5%90%8d%e4%ba%ba%e8%a6%aa%e5%ad%90%e7%94%9f%e6%b4%bb%e3%80%91%e6%af%8d%e6%84%9b%e6%bb%bf%e5%87%ba%e4%be%86%ef%bc%81%e5%b0%88%e8%a8%aa%e4%b8%bb%e6%92%ad%e5%aa%bd%e5%92%aa/',
  },
  {
    createdDate: '2022-11-14',
    title: '做好自己，才能成為其他角色！專訪斜槓媽咪張宇，一探她成為母親後的覺醒',
    tags: ['專訪', '花嫁'],
    redirectUrl: 'https://www.luxewed.asia/People/%e3%80%90%e8%8a%b1%e5%ab%81%e7%89%b9%e4%bc%81%e2%94%82%e5%90%8d%e4%ba%ba%e8%a6%aa%e5%ad%90%e7%94%9f%e6%b4%bb%e3%80%91%e5%81%9a%e5%a5%bd%e8%87%aa%e5%b7%b1%ef%bc%8c%e6%89%8d%e8%83%bd%e6%88%90%e7%82%ba/',
  },
  {
    createdDate: '2022-10-31',
    title: '幸福是自己給的！歷經挫折與低潮，重拾最自在的人生——陳艾熙',
    tags: ['專訪', '花嫁'],
    redirectUrl: 'https://www.luxewed.asia/People/%e3%80%90%e8%8a%b1%e5%ab%81%e7%89%b9%e4%bc%81%e2%94%82%e6%88%91%e7%9a%84%e7%be%8e%e9%ba%97%e7%94%9f%e5%ad%98%e4%b9%8b%e9%81%93%e3%80%91%e5%b9%b8%e7%a6%8f%e6%98%af%e8%87%aa%e5%b7%b1%e7%b5%a6%e7%9a%84/',
  },
  {
    createdDate: '2022-09-18',
    title: '獲得心靈的滿足，才能為家人迎來幸福！一窺「女王」從女孩成為人母的微妙變化',
    tags: ['專訪', '花嫁'],
    redirectUrl: 'https://www.luxewed.asia/People/%e3%80%90%e8%8a%b1%e5%ab%81%e7%89%b9%e4%bc%81%e2%94%82%e5%90%8d%e4%ba%ba%e8%a6%aa%e5%ad%90%e7%94%9f%e6%b4%bb%e3%80%91%e7%8d%b2%e5%be%97%e5%bf%83%e9%9d%88%e7%9a%84%e6%bb%bf%e8%b6%b3%ef%bc%8c%e6%89%8d/',
  },
  {
    createdDate: '2023-01-18',
    title: '貢獻畢生所學不遺餘力！專訪前職棒好手 –「豹子腿」方昶詠，如何打造不後悔的後棒球人生？',
    tags: ['專訪', '花嫁'],
    redirectUrl: 'https://www.luxewed.asia/People/%e3%80%90luxewed%e2%94%82%e6%88%91%e7%9a%84%e7%86%b1%e8%a1%80%e7%94%9f%e5%ad%98%e4%b9%8b%e9%81%93%e3%80%91%e8%b2%a2%e7%8d%bb%e7%95%a2%e7%94%9f%e6%89%80%e5%ad%b8%e4%b8%8d%e9%81%ba%e9%a4%98%e5%8a%9b/',
  },
  {
    createdDate: '2022-03-29',
    title: 'will Smith那一拳背後，原來是對老婆的支持與愛意',
    tags: ['外稿', 'FIGARO'],
    redirectUrl: 'https://www.madamefigaro.hk/wellness/will-smith-jada-pinkett-89100/',
  },
  {
    createdDate: '2022-04-06',
    title: 'wolfgang Tillmans 生平介紹',
    tags: ['文案', 'moom'],
    redirectUrl: 'https://moom.cat/tw/artist/wolfgang-tillmans',
  },
  {
    createdDate: '2022-04-06',
    title: 'Christopher Anderson 生平介紹',
    tags: ['文案', 'moom'],
    redirectUrl: 'https://moom.cat/tw/artist/christopher-anderson',
  },
  {
    createdDate: '2021-12-30',
    title: '浪漫約會首選！過節到「沾美西餐廳」享受情懷吧！',
    tags: ['外稿', 'readyGo'],
    redirectUrl: 'https://imreadygo.com/100401/',
  },
  {
    createdDate: '2022-03-25',
    title: '憑《犬山記》成首位二度入圍奧斯卡的女導演 Jane Campion 以鏡頭刻劃細膩情感，望力除業界性別不平等',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/magazine/topics/culture/jane-campion',
  },
  {
    createdDate: '2022-03-11',
    title: '用「廢棄牛骨」打造的再生插座 Elos，兼具永續與美學還能自由轉動角度',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2022/03/11/elos-souhaib-ghanmi/',
  },
  {
    createdDate: '2021-10-07',
    title: '入骨般地熱愛！站上國際舞台的舞蹈家許芳宜以身體創作自我療癒',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/career/fang-yi-sheu/?fbclid=IwAR0JHNf7gHuKmyigkCsrZ737iZmLkvJTtjHmsjM3X-rOy2O5c9GM9Gfixjo',
  },
  {
    createdDate: '2021-10-05',
    title: '藍瓶咖啡首度插旗大阪！打造味覺與視覺交融的城市咖啡館',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/10/05/blue-bottle-coffee/',
  },
  {
    createdDate: '2020-11-30',
    title: 'AMOUREUX 暖心紅禮盒',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/warmheartgift',
  },
  {
    createdDate: '2020-11-30',
    title: 'AMOUREUX 格調金禮盒',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/stylegold',
  },
  {
    createdDate: '2021-09-23',
    title: '基隆市區散散步｜用兩天一夜的時間到「雨都」療癒心靈，推薦「不觀光」的私藏小店',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/09/23/day-trip-to-keelung/',
  },
  {
    createdDate: '2021-09-23',
    title: '4:44 APPLE wATCH BAND 文案',
    tags: ['外稿', '444Studio'],
    redirectUrl: 'https://www.444studio-acc.com/products/apple-watch-stainless-steel-fine-small-wenqing-strap-black',
  },
  {
    createdDate: '2020-06-28',
    title: 'AMOUREUX 推出全新提袋設計，為婚宴注入奢華精品感',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/blog/2020/06/28',
  },
  {
    createdDate: '2021-01-03',
    title: '想和全世界的人宣告自己多幸福！輕奢喜餅 AMOUREUX 推出年度形象影片',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/blog/2021/01/03',
  },
  {
    createdDate: '2020-07-22',
    title: 'AMOUREUX 品牌故事',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/info-contact',
  },
  {
    createdDate: '2021-09-22',
    title: '就是要和別人不一樣！舉辦輕鬆又不失隆重的戶外婚禮，讓你親自接收所有愛的祝福',
    tags: ['外稿', 'amoureux'],
    redirectUrl: 'https://www.amoureux.com.tw/blog/2021/09/21/outdoor-wedding-venue',
  },
  {
    createdDate: '2021-09-17',
    title: '無懼轉換人生跑道！Jessica Ewing棄Google高薪厚職，獨創媲美Amazon的出版社',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/career/jessica-ewing/',
  },
  {
    createdDate: '2021-09-01',
    title: '著作被稱為非洲版《哈利波特》！Tomi Adeyemi 在文壇初試啼聲即晉升暢銷作家',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/career/tomi-adeyemi/',
  },
  {
    createdDate: '2021-07-16',
    title: '日本鳥取「植田正治攝影美術館」，喚醒人與土地的連結',
    tags: ['外稿', 'thefingerwords'],
    redirectUrl: 'https://thefingerwords.com/photography-gallery/',
  },
  {
    createdDate: '2021-09-08',
    title: '一窺日本女孩的「治癒系生活」！與工作和愛人為伍的浪漫日常',
    tags: ['外稿', 'thefingerwords'],
    redirectUrl: 'https://thefingerwords.com/romantic-everyday/',
  },
  {
    createdDate: '2020-12-08',
    title: '與旅人連結在地文化－熊本旅店 RESTERS BED&amp;CO.',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2020/12/08/resters-bed-and-co/',
  },
  {
    createdDate: '2020-12-24',
    title: '嚐山城美味、走民宿老闆才知道的秘境，現在正是「出發九份」的最好時節',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2020/12/24/one-night-in-jiufen/',
  },
  {
    createdDate: '2021-07-16',
    title: '帶一份療癒系土產回去吧！精選三家融入當地文化的日本超人氣伴手禮',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/07/16/japan-native-produce/',
  },
  {
    createdDate: '2021-08-12',
    title: '插畫界的裝傻擔當！日本藝術家 Nishiwaki Tadashi 畫出軟萌俏皮的獨特世界觀',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/08/12/nishiwaki-tadashi/',
  },
  {
    createdDate: '2021-09-15',
    title: '再造城市新美學！洛杉磯貨櫃屋轉型為無家者收容所「The Hilda L Solis Care First Village」',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/09/15/the-hilda-l-solis-care-first-village/',
  },
  {
    createdDate: '2021-10-29',
    title: '一個失誤就要NG重來！這些「一鏡到底」的 MV 刷新你對拍攝的想像',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/3-music-videos-filmed-in-one-shot/',
  },
  {
    createdDate: '2021-10-29',
    title: '每位女性都能在蜷川實花的作品中，看見自己的影子',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/career/ninagawa-mika/',
  },
  {
    createdDate: '2021-10-29',
    title: '奧斯卡史上第三位入圍最佳導演的女性，Sofia Coppola 用鏡頭替自己說話！',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/career/sofia-coppola/',
  },
  {
    createdDate: '2021-10-27',
    title: '延續西巴牙的奔放印象：巴塞隆納黃色公寓「Seven Lives Housing」，為街坊綻放熱情與活力',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/10/27/seven-lives-housing/',
  },
  {
    createdDate: '2021-11-08',
    title: '想成為地球最喜歡的公司！主打不破壞環境，美國有機棉服飾品牌「Pact」',
    tags: ['外稿', 'fingerwords'],
    redirectUrl: 'https://thefingerwords.com/american-organic-cotton-apparel-brand-pact/',
  },
  {
    createdDate: '2021-11-04',
    title: '要排隊的台南我才不去！這次就到二手書店挖寶、嘗不輸給法餐的牛肉湯，滿足想要出走的心',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/04/one-day-in-tainan/',
  },
  {
    createdDate: '2021-11-04',
    title: '將傳統韓屋翻新為時髦咖啡館，Bidam 讓南韓老宅綻放昔日被掩蓋的光芒',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/04/designtoken-bidam/',
  },
  {
    createdDate: '2021-11-02',
    title: '大熱影集《Normal People》原作者正是她！被譽為「千禧世代的代表作家」的Sally Rooney',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/magazine/topics/culture/sally-rooney?rq=Normal%20People',
  },
  {
    createdDate: '2021-10-29',
    title: '「沒有製作電影的經驗，但我就是去做了！」20 歲演員 Ella Greenwood 創辦製作公司，倡導心理健康議題',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/career/ella-greenwood/',
  },
  {
    createdDate: '2021-11-16',
    title: '「我並非極簡主義者。」設計純粹而有力，傳奇時裝大師 Jil Sander 不妥協的美學觀',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/magazine/topics/career/jil-sander?rq=%20Jil%20Sande',
  },
  {
    createdDate: '2021-11-08',
    title: '以廢棄馬桶作為媒材！印度設計師與藍陶工匠聯手打造「NewBlue」系列，賦予被丟棄的陶瓷全新生命',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/08/disharee-mathur-newblue/',
  },
  {
    createdDate: '2021-11-10',
    title: '今年就辦一個「霍格華茲」魔法派對，親手做海格版的生日蛋糕款待朋友吧！',
    tags: ['外稿', 'fingerwords'],
    redirectUrl: 'https://thefingerwords.com/harry-potter-party/',
  },
  {
    createdDate: '2021-11-05',
    title: '熱衷時尚且關懷社會！一窺芬蘭「美學家」Jenni Rotonen 的小精靈日常',
    tags: ['外稿', 'fingerwords'],
    redirectUrl: 'https://thefingerwords.com/jenni-rotonen/',
  },
  {
    createdDate: '2021-11-11',
    title: '百年煎餅、手工繡花和餐桌風景，帶一份台南土產回家吧！精選三家府城在地小店， 讓旅行回憶同步於你的日常',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/11/one-day-in-tainan-2/',
  },
  {
    createdDate: '2021-11-16',
    title: '因家庭巨變而踏上從政之路，台移民第二代吳弭成為波士頓首位女市長！',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/magazine/topics/career/michelle-wu?rq=%E5%90%B3%E5%BC%AD',
  },
  {
    createdDate: '2022-01-10',
    title: '關注島嶼群的藝文光譜！隨著小誌《島嶼城誌》從陸地航向周圍海洋，與自由靈魂相遇',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2022/01/10/insular-city-zine/',
  },
  {
    createdDate: '2021-12-22',
    title: '宜蘭市區散散步｜走訪獨立書店、啜飲單品咖啡，到能遠眺蘭陽平原的民宿住一晚！',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/12/22/yilan-trip/',
  },
  {
    createdDate: '2022-01-29',
    title: '質感雜誌《Kinfolk》團隊為「身邊有孩子的人」打造！《Kindling》捎來不具批判又趣味的嶄新思維',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2022/01/29/kinfolk-kindling/',
  },
  {
    createdDate: '2021-11-30',
    title: '為老房子軀殼注入年輕靈魂 − 踏進高雄「日和珈琲」，一嘗回到老家般的親切',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/30/goodvibe-coffee/',
  },
  {
    createdDate: '2021-11-23',
    title: '用小誌打造給罹癌者的粗略指南！英國小誌《Onco’zine》，揭露沒人願意繼續的「狗屎之旅」',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/11/23/cancer-oncozine/',
  },
  {
    createdDate: '2022-03-25',
    title: '以一支護手霜療癒身心，專訪 moi skincare 主理人 Peggy：「照顧好自己才是首要任務」',
    tags: ['專訪', 'women in work'],
    redirectUrl: 'https://wiw.hk/magazine/topics/culture/peggy-the-founder-of-moi-skincare?rq=moi',
  },
  {
    createdDate: '2021-10-19',
    title: '以老屋裸空間的本質向自然致意：隱身於審計新村的茶坊「兆兆茶苑」，在巷弄中悄然傳承台灣茶文化',
    tags: ['外稿', 'wonder'],
    redirectUrl: 'https://wonder.am/2021/10/19/zhaozhaotealounge/',
  },
  {
    createdDate: '2021-10-19',
    title: '以她們的手寫文字的溫度傳遞情感，帶領觀眾融入MV意境！',
    tags: ['外稿', 'women in work'],
    redirectUrl: 'https://wiw.hk/topics/culture/handwriting-in-music-video/',
  },
]
